name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: Install dependencies and build
        run: |
          npm install
          npm run build:browser

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./src/ui/dist/browser/

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
